services:

  volume-fixer:
    image: alpine
    container_name: volume-fixer
    volumes:
      - spark-data-volume:/data
    command: chown -R 1001:1001 /data

  # SPARK DATA GENERATOR
  spark-master-producer:
    image: bitnamilegacy/spark:3.5.1 
    container_name: spark-master-producer
    depends_on:
      volume-fixer:
        condition: service_completed_successfully
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "${SPARK_PRODUCER_WEB_UI_PORT}:8080"
      - "6060:7077"

  spark-worker-producer:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-worker-producer
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-producer:7077
      - SPARK_WORKER_MEMORY=${SPARK_PRODUCER_WORKERS_MEM}
      - SPARK_WORKER_CORES=${SPARK_PRODUCER_WORKERS_CORES} 
    depends_on:
      - spark-master-producer
    volumes:
      - spark-data-volume:/data

  # LAUNCH PYTHON SCRIPT TO GENERATE DATA
  spark-submitter-producer:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-submitter-producer
    depends_on:
      - spark-master-producer
      - spark-worker-producer
    environment:
      - NUM_ROWS=${NUM_ROWS}
      - NUM_SHARDS=${NUM_SHARDS}
    volumes:
      - ./spark:/opt/bitnami/spark/jobs
      - spark-data-volume:/data
    command: bash /opt/bitnami/spark/jobs/launch-producer.sh

  # Queue
  redis:
    image: redis:alpine
    container_name: redis-queue
    ports:
      - "${REDIS_PORT}:6379"

  # HTTP WORKERS
  http-worker:
    build: ./http
    deploy:
      replicas: ${HTTP_WORKERS_REPLICAS}
    depends_on:
      - redis
    environment:
      - TARGET_API=${API_ADDR}
      - API_PORT=${API_PORT}
      - REDIS_HOST=redis
    volumes:
      - ./http:/scripts
      - spark-data-volume:/data

volumes:
  spark-data-volume: